# Generated by Django 3.1.3 on 2020-12-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='witten_by',
            new_name='written_by',
        ),
    ]
