# Generated by Django 3.1.3 on 2020-12-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fx', 'Forex'), ('dc', 'crypto'), ('ix', 'indices'), ('cm', 'commodities'), ('ed', 'educational')], default=('fx', 'Forex'), max_length=50),
        ),
    ]
